Bracket missing
exit 1 should only be executed when download failed...

diff --git a/ubuntu_14.04/Vagrantfile b/ubuntu_14.04/Vagrantfile
--- a/ubuntu_14.04/Vagrantfile
+++ b/ubuntu_14.04/Vagrantfile
@@ -87,13 +87,13 @@ Vagrant.configure(2) do |config|
   # pulls latest master from Jenkins, imports two sample keys
   config.vm.provision :shell, privileged: false, inline: <<-SHELL
     echo 'Downloading latest libreoffice'
-    wget -q http://librebuildix.cib.de:8080/job/LibreOffice%20master%20Linux%2064bit/label=linux-builder/lastSuccessfulBuild/artifact/LibreOffice_6.0.0.0.alpha0_Linux_x86-64_deb.tar.gz || echo "Cannot download LibreOffice" && exit 1
+    wget -q http://librebuildix.cib.de:8080/job/LibreOffice%20master%20Linux%2064bit/label=linux-builder/lastSuccessfulBuild/artifact/LibreOffice_6.0.0.0.alpha0_Linux_x86-64_deb.tar.gz || (echo "Cannot download LibreOffice" && exit 1)
     tar -xf LibreOffice_6.0.0.0.alpha0_Linux_x86-64_deb.tar.gz
     sudo bash -c 'cd LibreOffice_6.0.0.0.alpha0_Linux_x86-64_deb/DEBS && dpkg -i *.deb'
   SHELL
   config.vm.provision :shell, privileged: false, inline: <<-SHELL
     echo 'Installing latest libreoffice langpacks'
-    wget -q http://librebuildix.cib.de:8080/job/LibreOffice%20master%20Linux%2064bit/label=linux-builder/lastSuccessfulBuild/artifact/LibreOffice_6.0.0.0.alpha0_Linux_x86-64_deb_langpack_de.tar.gz || echo "Cannot download LibreOffice language pack" && exit 1
+    wget -q http://librebuildix.cib.de:8080/job/LibreOffice%20master%20Linux%2064bit/label=linux-builder/lastSuccessfulBuild/artifact/LibreOffice_6.0.0.0.alpha0_Linux_x86-64_deb_langpack_de.tar.gz || (echo "Cannot download LibreOffice language pack" && exit 1)
     tar -xf LibreOffice_6.0.0.0.alpha0_Linux_x86-64_deb_langpack_de.tar.gz
     sudo bash -c 'cd LibreOffice_6.0.0.0.alpha0_Linux_x86-64_deb_langpack_de/DEBS/ && dpkg -i *.deb'
   SHELL
